# Pandas Exercises
Time to test your new pandas skills! Use the <tt>population_by_county.csv</tt> file in the Data folder to complete the tasks in bold below!

#### 1. Import pandas and read in the <tt>population_by_county.csv</tt> file into a dataframe called <tt>pop</tt>.

In [1]:
import pandas as pd

#### 2. Show the head of the dataframe

In [2]:
data = pd.read_csv('population_by_county.csv')
print(data.head())

             County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054

#### 3. What are the column names?

In [3]:
print(data.info())
print(data.describe())
# display column names
print(data.columns)

<class 'pandas.DataFrame'>
RangeIndex: 3142 entries, 0 to 3141
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   County           3142 non-null   str
 1   State            3142 non-null   str
 2   2010Census       3142 non-null   int64
 3   2017PopEstimate  3142 non-null   int64
dtypes: int64(2), str(2)
memory usage: 98.3 KB
None
         2010Census  2017PopEstimate
count  3.142000e+03     3.142000e+03
mean   9.826402e+04     1.036662e+05
std    3.129465e+05     3.330502e+05
min    8.200000e+01     8.800000e+01
25%    1.111450e+04     1.089975e+04
50%    2.587200e+04     2.583850e+04
75%    6.678000e+04     6.771750e+04
max    9.818605e+06     1.016351e+07
Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='str')

In [ ]:
# DON'T WRITE HERE

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')

<strong>4. How many States are represented in this data set?</strong> <em>Note: the data includes the District of Columbia</em>

In [5]:
# DON'T WRITE HERE
number_of_states = data['State'].nunique()
print(f'The number of unique states in the dataset is: {number_of_states}')

The number of unique states in the dataset is: 51

#### 5. Get a list or array of all the states in the data set.

In [6]:
# list or array of unique states
unique_states = data['State'].unique()
print(f'The unique states in the dataset are: {unique_states}')

The unique states in the dataset are: <StringArray>
[      'South Carolina',            'Louisiana',             'Virginia',
                'Idaho',                 'Iowa',             'Kentucky',
             'Missouri',             'Oklahoma',             'Colorado',
             'Illinois',              'Indiana',          'Mississippi',
             'Nebraska',         'North Dakota',                 'Ohio',
         'Pennsylvania',           'Washington',            'Wisconsin',
              'Vermont',            'Minnesota',              'Florida',
       'North Carolina',           'California',             'New York',
              'Wyoming',             'Michigan',               'Alaska',
             'Maryland',               'Kansas',            'Tennessee',
                'Texas',                'Maine',              'Arizona',
              'Georgia',             'Arkansas',           'New Jersey',
         'South Dakota',              'Alabama',               'Oregon',
        'West Virginia',        'Massachusetts',                 'Utah',
              'Montana',        'New Hampshire',           'New Mexico',
         'Rhode Island',               'Nevada', 'District of Columbia',
          'Connecticut',               'Hawaii',             'Delaware']
Length: 51, dtype: str

In [ ]:
# DON'T WRITE HERE

array(['South Carolina', 'Louisiana', 'Virginia', 'Idaho', 'Iowa',
       'Kentucky', 'Missouri', 'Oklahoma', 'Colorado', 'Illinois',
       'Indiana', 'Mississippi', 'Nebraska', 'North Dakota', 'Ohio',
       'Pennsylvania', 'Washington', 'Wisconsin', 'Vermont', 'Minnesota',
       'Florida', 'North Carolina', 'California', 'New York', 'Wyoming',
       'Michigan', 'Alaska', 'Maryland', 'Kansas', 'Tennessee', 'Texas',
       'Maine', 'Arizona', 'Georgia', 'Arkansas', 'New Jersey',
       'South Dakota', 'Alabama', 'Oregon', 'West Virginia',
       'Massachusetts', 'Utah', 'Montana', 'New Hampshire', 'New Mexico',
       'Rhode Island', 'Nevada', 'District of Columbia', 'Connecticut',
       'Hawaii', 'Delaware'], dtype=object)

#### 6. What are the five most common County names in the U.S.?

In [7]:
# five most common county names
most_common_counties = data['County'].value_counts().head(5)
print(f'The five most common county names in the dataset are:\n{most_common_counties}')

The five most common county names in the dataset are:
County
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: count, dtype: int64

In [ ]:
# DON'T WRITE HERE

Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: County, dtype: int64

#### 7. What are the top 5 most populated Counties according to the 2010 Census?

In [8]:
# top 5 most populated counties in the according to 2010 census
top_5_populated_counties = data.sort_values(by='2010Census', ascending=False).head(5)
print(f'The top 5 most populated counties according to the 2010 census are:\n{top_5_populated_counties[["County", "2010Census"]]}')

The top 5 most populated counties according to the 2010 census are:
                  County  2010Census
1713  Los Angeles County     9818605
628          Cook County     5194675
1209       Harris County     4092459
1784     Maricopa County     3817117
2501    San Diego County     3095313

In [ ]:
# DON'T WRITE HERE

                  County       State  2010Census  2017PopEstimate
1713  Los Angeles County  California     9818605         10163507
628          Cook County    Illinois     5194675          5211263
1209       Harris County       Texas     4092459          4652980
1784     Maricopa County     Arizona     3817117          4307033
2501    San Diego County  California     3095313          3337685

#### 8. What are the top 5 most populated States according to the 2010 Census?

In [11]:
# data.groupby('State')['2010Census'].sum().sort_values(ascending=False).head(5)
# data.groupby('State')['2010Census'].sum()

data.groupby('State')['2010Census'].sum()

data.groupby('State').sum().drop('County', axis=1).sort_values('2010Census', ascending=False).head(5)

            2010Census  2017PopEstimate
State
California    37253956         39536653
Texas         25145561         28304596
New York      19378102         19849399
Florida       18801310         20984400
Illinois      12830632         12802023

In [12]:
# DON'T WRITE HERE
# which is the top 10 county which has highest median 2017PopEstimate

data.groupby('County')['2017PopEstimate'].median().sort_values(ascending=False).head(10)

County
Los Angeles County       10163507.0
Maricopa County           4307033.0
San Diego County          3337685.0
Miami-Dade County         2751796.0
Riverside County          2423266.0
Queens County             2358582.0
Harris County             2343447.5
San Bernardino County     2157404.0
Tarrant County            2054475.0
Bexar County              1958578.0
Name: 2017PopEstimate, dtype: float64

In [14]:
data.groupby('County').agg({'2017PopEstimate': ['median', 'mean', 'std', 'max']}).sort_values(('2017PopEstimate', 'median'), ascending=False).head(10)

                      2017PopEstimate
                               median        mean           std       max
County
Los Angeles County         10163507.0  10163507.0           NaN  10163507
Maricopa County             4307033.0   4307033.0           NaN   4307033
San Diego County            3337685.0   3337685.0           NaN   3337685
Miami-Dade County           2751796.0   2751796.0           NaN   2751796
Riverside County            2423266.0   2423266.0           NaN   2423266
Queens County               2358582.0   2358582.0           NaN   2358582
Harris County               2343447.5   2343447.5  3.266172e+06   4652980
San Bernardino County       2157404.0   2157404.0           NaN   2157404
Tarrant County              2054475.0   2054475.0           NaN   2054475
Bexar County                1958578.0   1958578.0           NaN   1958578

#### 9. How many Counties have 2010 populations greater than 1 million?

In [19]:
# how many countes have 2010 poplutation greater than 1 million
data[data['2010Census'] > 1000000].shape[0]

data['2010Census'].gt(1000000).sum()

data['2010Census'].gt(1000000).sum()

np.int64(39)

In [ ]:
# DON'T WRITE HERE

39

#### 10. How many Counties don't have the word "County" in their name?

In [20]:
# how many counties don't have word 'County' in their name

def check_county_name(county_name):
    if 'County' not in county_name:
        return True
    else:
        return False

data['County'].apply(check_county_name).sum()

np.int64(135)

In [ ]:
# DON'T WRITE HERE

135

#### 11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [22]:
# CODE HERE
# Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

data['Percent_Change'] = ((data['2017PopEstimate'] - data['2010Census']) / data['2010Census']) * 100
data.head()

# USE THIS TO SHOW THE RESULT

,County,State,2010Census,2017PopEstimate,Percent_Change
0,Abbeville County,South Carolina,25417,24722,-2.734390
1,Acadia Parish,Louisiana,61773,62590,1.322584
2,Accomack County,Virginia,33164,32545,-1.866482
3,Ada County,Idaho,392365,456849,16.434697
4,Adair County,Iowa,7682,7054,-8.174954

In [ ]:
# DON'T WRITE HERE

,County,State,2010Census,2017PopEstimate,PercentChange
0,Abbeville County,South Carolina,25417,24722,-2.734390
1,Acadia Parish,Louisiana,61773,62590,1.322584
2,Accomack County,Virginia,33164,32545,-1.866482
3,Ada County,Idaho,392365,456849,16.434697
4,Adair County,Iowa,7682,7054,-8.174954

<strong>Bonus: What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?</strong><br>This will take several lines of code, as it requires a recalculation of PercentChange.

In [ ]:
# CODE HERE

In [ ]:
# DON'T WRITE HERE

                      2010Census  2017PopEstimate  PercentChange
State
District of Columbia      601723           693972      15.330808
Texas                   25145561         28304596      12.562993
North Dakota              672591           755393      12.310899
Utah                     2763885          3101833      12.227282
Florida                 18801310         20984400      11.611372

# GREAT JOB!